import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // choose what you need
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} font-roboto antialiased `}>
        {/* <div className="lg:flex hidden bg-[radial-gradient(circle_at_center,_rgba(37,99,235,0.35)_0%,_rgba(255,255,255,0.9)_40%)] h-screen w-screen fixed top-0 left-[30%]"></div> */}
        {children}
      </body>
    </html>
  );
}
